spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jingzheng?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            maxActive: 10
            maxWait: -1
            maxIdle: 8
            minIdle: 0
        timeout: 0